const FETCH_BLOGS_SUCCESS = "FETCH_BLOGS_SUCCESS";
const FETCH_BLOGS_FAILURE = "FETCH_BLOGS_FAILURE";
const FETCH_BLOG_FAILURE = "FETCH_BLOG_FAILURE";
const FETCH_BLOG_SUCCESS = "FETCH_BLOG_SUCCESS";
const FILTER_POST_FAILURE = "FILTER_POST_FAILURE";
const FILTER_POST_SUCCESS = "FILTER_POST_SUCCESS";
const LOADING_STATE = "LOADING_STATE";
const SET_ACTIVE_SEARCH = "SET_ACTIVE_SEARCH";
export {
    FETCH_BLOGS_FAILURE,
    FETCH_BLOGS_SUCCESS,
    FETCH_BLOG_SUCCESS,
    FETCH_BLOG_FAILURE,
    FILTER_POST_SUCCESS,
    FILTER_POST_FAILURE,
    SET_ACTIVE_SEARCH,
    LOADING_STATE,
}